### ISSUE TITLE
Download Lowest Quality when Preferred Quality not Available.

### ISSUE THREAD

**Issue by Midnex** [Jodagito/YouTubeDownloader#5]
Linux Mint 19.3 x64
Destination path = 
Video quality = 1080
Audio quality = 160
When unavailable = Lowest

Bug: When unavailable = Lowest doesn't appear to work.
url: https://www.youtube.com/watch?v=oIN488Ldg9k

`Traceback (most recent call last):
  File "YouTubeDownloader.py", line 300, in <module>
    main()
  File "YouTubeDownloader.py", line 44, in main
    return settings_menu()
  File "YouTubeDownloader.py", line 177, in settings_menu
    return list_settings()
  File "YouTubeDownloader.py", line 269, in list_settings
    return settings_menu()
  File "YouTubeDownloader.py", line 177, in settings_menu
    return list_settings()
  File "YouTubeDownloader.py", line 269, in list_settings
    return settings_menu()
  File "YouTubeDownloader.py", line 183, in settings_menu
    return main()
  File "YouTubeDownloader.py", line 42, in main
    return downloads_menu()
  File "YouTubeDownloader.py", line 82, in downloads_menu
    return main()
  File "YouTubeDownloader.py", line 42, in main
    return downloads_menu()
  File "YouTubeDownloader.py", line 78, in downloads_menu
    download_video(pytube_object)
  File "YouTubeDownloader.py", line 148, in download_video
    type='video', res=default_quality).order_by('resolution').desc().all()[0]
IndexError: list index out of range
`

**Comment by Midnex** [comment]
Seems to be an issue with video format, below also works for audio but not video.
https://www.youtube.com/watch?v=CZ3wIuvmHeM
